version: 2
updates:
  # Automatically track and update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      action-updates:
        patterns:
          - "*"

  # Automatically track and update Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"